name: modul4kel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.3.3
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  dio: ^5.4.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^1.1.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
